export const LOGIN_LOADING: string = "app/auth/LOGIN_LOADING";
export const LOGIN_SUCCESS: string = "app/auth/LOGIN_SUCCESS";
export const LOGIN_ERROR: string = "app/auth/LOGIN_ERROR";
export const LOGIN_RESET: string = "app/auth/LOGIN_RESET";
export const GET_USER_LOADING: string = "app/user/GET_USER_LOADING";
export const GET_USER_SUCCESS: string = "app/user/GET_USER_SUCCESS";
export const GET_USER_ERROR: string = "app/user/GET_USER_ERROR";
export const GET_PATIENTS_LOADING: string = "app/user/GET_PATIENTS_LOADING";
export const GET_PATIENTS_SUCCESS: string = "app/user/GET_PATIENTS_SUCCESS";
export const GET_PATIENTS_ERROR: string = "app/user/GET_PATIENTS_ERROR";
export const GET_PATIENT_LOADING: string = "app/user/GET_PATIENT_LOADING";
export const GET_PATIENT_SUCCESS: string = "app/user/GET_PATIENT_SUCCESS";
export const GET_PATIENT_ERROR: string = "app/user/GET_PATIENT_ERROR";
export const GET_PATIENT_RESET: string = "app/user/GET_PATIENT_RESET";
export const ADD_PATIENT_LOADING: string = "app/user/ADD_PATIENT_LOADING";
export const ADD_PATIENT_SUCCESS: string = "app/user/ADD_PATIENT_SUCCESS";
export const ADD_PATIENT_ERROR: string = "app/user/ADD_PATIENT_ERROR";
export const ADD_PATIENT_RESET: string = "app/user/ADD_PATIENT_RESET";
export const UPDATE_PATIENT_LOADING: string = "app/user/UPDATE_PATIENT_LOADING";
export const UPDATE_PATIENT_SUCCESS: string = "app/user/UPDATE_PATIENT_SUCCESS";
export const UPDATE_PATIENT_ERROR: string = "app/user/UPDATE_PATIENT_ERROR";
export const UPDATE_PATIENT_RESET: string = "app/user/UPDATE_PATIENT_RESET";
export const UPLOAD_DOCUMENT_LOADING: string =
  "app/user/UPLOAD_DOCUMENT_LOADING";
export const UPLOAD_DOCUMENT_SUCCESS: string =
  "app/user/UPLOAD_DOCUMENT_SUCCESS";
export const UPLOAD_DOCUMENT_ERROR: string = "app/user/UPLOAD_DOCUMENT_ERROR";
export const UPLOAD_DOCUMENT_RESET: string = "app/user/UPLOAD_DOCUMENT_RESET";
export const SET_USER: string = "app/user/SET_USER";
